"""Build-time snapshot of the 226 ClinicalTrials.gov `LocationCountry` spellings.

Fetches the unfiltered value list (allowed on `/stats/field/values`, unlike a filtered query;
see PLAN.md §5.1) and writes it into `src/ctviz/catalog/countries.py` as `COUNTRIES`, so a live
API change can never silently break request coercion. Run with `uv run python
scripts/snapshot_countries.py`.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import httpx

from ctviz.config import CTGOV_BASE_URL

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src" / "ctviz" / "catalog" / "countries.py"


def fetch_country_names() -> list[str]:
    """Return every distinct `LocationCountry` value the API has ever seen."""
    response = httpx.get(
        f"{CTGOV_BASE_URL}/stats/field/values",
        params={"fields": "LocationCountry"},
        timeout=30.0,
    )
    response.raise_for_status()
    entries = response.json()
    values = entries[0]["topValues"]
    return sorted({item["value"].strip() for item in values})


def render_module(names: list[str]) -> str:
    """Render the generated `countries.py` source, one name per line for a readable diff."""
    today = datetime.now(tz=UTC).date().isoformat()
    lines = ",\n".join(f'    "{name}"' for name in names)
    return (
        f"# Generated by scripts/snapshot_countries.py on {today}. Do not edit by hand.\n"
        "# ruff: noqa: RUF001 -- some API-supplied names use non-ASCII punctuation verbatim.\n"
        '"""The ClinicalTrials.gov `LocationCountry` spellings, snapshotted from the live API."""\n'
        "\n"
        "COUNTRIES: frozenset[str] = frozenset(\n"
        "    {\n"
        f"{lines},\n"
        "    }\n"
        ")\n"
    )


def main() -> None:
    """Fetch the current country list and overwrite `catalog/countries.py`."""
    names = fetch_country_names()
    OUTPUT_PATH.write_text(render_module(names))
    print(f"Wrote {len(names)} countries to {OUTPUT_PATH}")  # noqa: T201


if __name__ == "__main__":
    main()
